image: alpine/git:2.43.0

pipelines:
  branches:
    master:
      - step:
          name: Mirror master to GitHub
          clone:
            depth: full
          script:
            - git push "https://x-access-token:${GITHUB_TOKEN}@github.com/barbaragavalda/vm-docker.git" master --tags
