#
# Builds and runs all docker containers to start a new VM
# @file docker-compose.yml

version: '3.3'
services:
 php:
  build: './system/docker/php'
  container_name: php
  depends_on:
   - mariadb
  networks:
   - backend
  environment:
   MYSQL_USER: optisistem
   MYSQL_PASSWORD: rtZYS9wJ7HWWNKdvqKJJR3B4AuWQ7WTgbwJXSrTBKJXyUX2pxFbPxVkuMkNEWGqv
   MYSQL_HOST: mariadb
  restart: always
  volumes:
  - ./src/:/var/www/html
 mariadb:
  build: './system/docker/mariadb'
  container_name: mariadb
  networks:
   - backend
  environment:
   MYSQL_ROOT_PASSWORD: 8S6yTBCh9vFeKcs7yrHgZ2YcVQPYHI9cQGGHekkDnDxMFJ2LhUKhp8VNFcUuG8pA
   MYSQL_USER: optisistem
   MYSQL_PASSWORD: rtZYS9wJ7HWWNKdvqKJJR3B4AuWQ7WTgbwJXSrTBKJXyUX2pxFbPxVkuMkNEWGqv
   MYSQL_ALLOW_EMPTY_PASSWORD: 0
   MYSQL_RANDOM_ROOT_PASSWORD: 0
  restart: always
  ports:
   - "3306:3306"
 apache:
  build: './system/docker/apache'
  container_name: apache
  depends_on:
   - php
   - mariadb
  networks:
   - backend
   - frontend
  ports:
   - "80:80/tcp"
   - "443:443/tcp"
  restart: always
  volumes:
  - ./src/:/usr/local/apache2/htdocs
networks:
  backend:
  frontend: