#
# Builds and runs all docker containers to start a new VM
# @file docker-compose.yml

services:
 php:
  build: './system/docker/php'
  container_name: php
  depends_on:
   - mariadb
  networks:
   - backend
  environment:
   MYSQL_USER: optisistem
   MYSQL_PASSWORD: rtZYS9wJ7HWWNK
   MYSQL_HOST: mariadb
  restart: always
  volumes:
  - ./storage/src/:/var/www/html
  - ./storage/id_rsa.pub:/root/.ssh/id_rsa
 mariadb:
  build: './system/docker/mariadb'
  container_name: mariadb
  networks:
   - backend
  environment:
   MYSQL_ROOT_PASSWORD: 8S6yTBCh9vFeKcs7yrHgZ2YcVQPYHI9cQGGHekkDnDxMFJ2LhUKhp8VNFcUuG8pA
   MYSQL_ALLOW_EMPTY_PASSWORD: 0
   MYSQL_RANDOM_ROOT_PASSWORD: 0
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  restart: always
  ports:
   - "3306:3306"
  volumes:
   - ./storage/database/:/var/lib/mysql/
 apache:
  build: './system/docker/apache'
  container_name: apache
  depends_on:
   - php
   - mariadb
  networks:
   - backend
   - frontend
  ports:
   - "80:80/tcp"
   - "443:443/tcp"
  restart: always
  volumes:
  - ./storage/config/apache/:/usr/local/apache2/conf/vhosts
  - ./storage/src/:/usr/local/apache2/htdocs
networks:
  backend:
  frontend: