CREATE USER 'optisistem' IDENTIFIED BY 'rtZYS9wJ7HWWNKdvqKJJR3B4AuWQ7WTgbwJXSrTBKJXyUX2pxFbPxVkuMkNEWGqv';
GRANT ALL PRIVILEGES ON *.* TO 'optisistem'@'%' IDENTIFIED BY 'rtZYS9wJ7HWWNKdvqKJJR3B4AuWQ7WTgbwJXSrTBKJXyUX2pxFbPxVkuMkNEWGqv';
FLUSH PRIVILEGES;